return {
  {
    model = `mp_m_freemode_01`,
    headOverlays = {
      beard = { color = 0, style = 0, secondColor = 0, opacity = 1 },
      complexion = { color = 0, style = 0, secondColor = 0, opacity = 0 },
      bodyBlemishes = { color = 0, style = 0, secondColor = 0, opacity = 0 },
      blush = { color = 0, style = 0, secondColor = 0, opacity = 0 },
      lipstick = { color = 0, style = 0, secondColor = 0, opacity = 0 },
      blemishes = { color = 0, style = 0, secondColor = 0, opacity = 0 },
      eyebrows = { color = 0, style = 0, secondColor = 0, opacity = 1 },
      makeUp = { color = 0, style = 0, secondColor = 0, opacity = 0 },
      sunDamage = { color = 0, style = 0, secondColor = 0, opacity = 0 },
      moleAndFreckles = { color = 0, style = 0, secondColor = 0, opacity = 0 },
      chestHair = { color = 0, style = 0, secondColor = 0, opacity = 1 },
      ageing = { color = 0, style = 0, secondColor = 0, opacity = 1 },
    },
    components = {
      { texture = 0, drawable = 0,  component_id = 0 },
      { texture = 0, drawable = 0,  component_id = 1 },
      { texture = 0, drawable = 0,  component_id = 2 },
      { texture = 0, drawable = 0,  component_id = 5 },
      { texture = 0, drawable = 0,  component_id = 7 },
      { texture = 0, drawable = 0,  component_id = 9 },
      { texture = 0, drawable = 0,  component_id = 10 },
      { texture = 0, drawable = 15, component_id = 11 },
      { texture = 0, drawable = 15, component_id = 8 },
      { texture = 0, drawable = 15, component_id = 3 },
      { texture = 0, drawable = 34, component_id = 6 },
      { texture = 0, drawable = 61, component_id = 4 },
    },
    props = {
      { prop_id = 0, drawable = -1, texture = -1 },
      { prop_id = 1, drawable = -1, texture = -1 },
      { prop_id = 2, drawable = -1, texture = -1 },
      { prop_id = 6, drawable = -1, texture = -1 },
      { prop_id = 7, drawable = -1, texture = -1 },
    }
  },
  {
    model = `mp_f_freemode_01`,
    headBlend = {
      shapeMix = 0.3,
      skinFirst = 0,
      shapeFirst = 31,
      skinSecond = 0,
      shapeSecond = 0,
      skinMix = 0,
      thirdMix = 0,
      shapeThird = 0,
      skinThird = 0,
    },
    hair = {
      color = 0,
      style = 15,
      texture = 0,
      highlight = 0
    },
    headOverlays = {
      chestHair = { secondColor = 0, opacity = 0, color = 0, style = 0 },
      bodyBlemishes = { secondColor = 0, opacity = 0, color = 0, style = 0 },
      beard = { secondColor = 0, opacity = 0, color = 0, style = 0 },
      lipstick = { secondColor = 0, opacity = 0, color = 0, style = 0 },
      complexion = { secondColor = 0, opacity = 0, color = 0, style = 0 },
      blemishes = { secondColor = 0, opacity = 0, color = 0, style = 0 },
      moleAndFreckles = { secondColor = 0, opacity = 0, color = 0, style = 0 },
      makeUp = { secondColor = 0, opacity = 0, color = 0, style = 0 },
      ageing = { secondColor = 0, opacity = 1, color = 0, style = 0 },
      eyebrows = { secondColor = 0, opacity = 1, color = 0, style = 0 },
      blush = { secondColor = 0, opacity = 0, color = 0, style = 0 },
      sunDamage = { secondColor = 0, opacity = 0, color = 0, style = 0 },
    },
    components = {
      { drawable = 0,  component_id = 0,  texture = 0 },
      { drawable = 0,  component_id = 1,  texture = 0 },
      { drawable = 0,  component_id = 2,  texture = 0 },
      { drawable = 0,  component_id = 5,  texture = 0 },
      { drawable = 0,  component_id = 7,  texture = 0 },
      { drawable = 0,  component_id = 9,  texture = 0 },
      { drawable = 0,  component_id = 10, texture = 0 },
      { drawable = 15, component_id = 3,  texture = 0 },
      { drawable = 15, component_id = 11, texture = 3 },
      { drawable = 14, component_id = 8,  texture = 0 },
      { drawable = 15, component_id = 4,  texture = 3 },
      { drawable = 35, component_id = 6,  texture = 0 },
    },
    props = {
      { prop_id = 0, drawable = -1, texture = -1 },
      { prop_id = 1, drawable = -1, texture = -1 },
      { prop_id = 2, drawable = -1, texture = -1 },
      { prop_id = 6, drawable = -1, texture = -1 },
      { prop_id = 7, drawable = -1, texture = -1 },
    }
  }
}
